<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assistant" nsURI="http://www.eclipse.org/Papyrus/2014/diagram/assistant"
    nsPrefix="assistant">
  <eClassifiers xsi:type="ecore:EClass" name="AssistedElementTypeFilter" eSuperTypes="../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Matches element types referenced as assisted by this model"/>
    </eAnnotations>
    <eOperations name="getProvider" ordered="false" lowerBound="1" eType="#//ModelingAssistantProvider">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" ordered="false"
        lowerBound="1" eType="#//ModelingAssistantProvider" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelingAssistantProvider" eSuperTypes="#//IModelingAssistantProvider">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>From package assistantapi.&lt;/p>"/>
    </eAnnotations>
    <eOperations name="getElementTypes" ordered="false" upperBound="-1" eType="#//ElementType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getClientContext" ordered="false" lowerBound="1" eType="#//ClientContext">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getElementType" ordered="false" lowerBound="1" eType="#//ElementType">
      <eParameters name="id" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eOperations>
    <eOperations name="getExcludedElementTypes" ordered="false" upperBound="-1" eType="#//ElementType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getRelationshipTypes" ordered="false" upperBound="-1" eType="#//ElementType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="isRelationshipType" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="elementType" ordered="false" lowerBound="1" eType="#//ElementType"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assistant" ordered="false"
        upperBound="-1" eType="#//Assistant" changeable="false" volatile="true" transient="true"
        derived="true" eOpposite="#//Assistant/provider">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilter" ordered="false"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="popupAssistant" ordered="false"
        upperBound="-1" eType="#//PopupAssistant" containment="true" eOpposite="#//PopupAssistant/owningProvider">
      <eAnnotations source="subsets" references="#//ModelingAssistantProvider/assistant"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectionAssistant" ordered="false"
        upperBound="-1" eType="#//ConnectionAssistant" containment="true" eOpposite="#//ConnectionAssistant/owningProvider">
      <eAnnotations source="subsets" references="#//ModelingAssistantProvider/assistant"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" ordered="false"
        unique="false" upperBound="-1" eType="#//ElementType" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The element types supported by the provider."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementTypeID" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The identifiers of element types supported by the provider."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientContext" ordered="false"
        unique="false" lowerBound="1" eType="#//ClientContext" changeable="false"
        volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The element types supported by the provider."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientContextID" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The identifiers of element types supported by the provider."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludedElementType" ordered="false"
        unique="false" upperBound="-1" eType="#//ElementType" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Element types that the provider will never return as popup or connection assistants.&#xA;This implies that inferred element types specializing any of these excluded types also will not be provided as assistants."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludedElementTypeID"
        ordered="false" upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifiers of element types that the provider will never return as popup or connection assistants.&#xA;This implies that inferred element types specializing any of these excluded types also will not be provided as assistants."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipType" ordered="false"
        unique="false" upperBound="-1" eType="#//ElementType" changeable="false" volatile="true"
        transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The element types supported by the provider."/>
      </eAnnotations>
      <eAnnotations source="subsets" references="#//ModelingAssistantProvider/elementType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipTypeID" ordered="false"
        upperBound="-1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The identifiers of element types supported by the provider."/>
      </eAnnotations>
      <eAnnotations source="subsets" references="#//ModelingAssistantProvider/elementTypeID"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assistant" abstract="true">
    <eOperations name="getElementType" ordered="false" lowerBound="1" eType="#//ElementType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementTypeID" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" ordered="false"
        unique="false" lowerBound="1" eType="#//ElementType" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" ordered="false"
        lowerBound="1" eType="#//ModelingAssistantProvider" changeable="false" volatile="true"
        transient="true" derived="true" eOpposite="#//ModelingAssistantProvider/assistant">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ElementType" instanceClassName="org.eclipse.gmf.runtime.emf.type.core.IElementType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>From package assistantapi.&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PopupAssistant" eSuperTypes="#//Assistant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilter" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter"
        containment="true">
      <eAnnotations source="subsets" references="#//PopupAssistant/filter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningProvider" ordered="false"
        lowerBound="1" eType="#//ModelingAssistantProvider" eOpposite="#//ModelingAssistantProvider/popupAssistant">
      <eAnnotations source="subsets" references="#//Assistant/provider"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionAssistant" eSuperTypes="#//Assistant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFilter" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSourceFilter" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter"
        containment="true">
      <eAnnotations source="subsets" references="#//ConnectionAssistant/sourceFilter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFilter" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTargetFilter" ordered="false"
        eType="ecore:EClass ../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter"
        containment="true">
      <eAnnotations source="subsets" references="#//ConnectionAssistant/targetFilter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningProvider" ordered="false"
        lowerBound="1" eType="#//ModelingAssistantProvider" eOpposite="#//ModelingAssistantProvider/connectionAssistant">
      <eAnnotations source="subsets" references="#//Assistant/provider"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ClientContext" instanceClassName="org.eclipse.gmf.runtime.emf.type.core.IClientContext"/>
  <eClassifiers xsi:type="ecore:EClass" name="IModelingAssistantProvider" instanceClassName="org.eclipse.gmf.runtime.emf.ui.services.modelingassistant.IModelingAssistantProvider"
      abstract="true" interface="true" eSuperTypes="#//IProvider">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>From package assistantapi.&lt;/p>"/>
    </eAnnotations>
    <eOperations name="getTypes" ordered="false" upperBound="-1" eType="#//ElementType">
      <eParameters name="hint" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eParameters name="data" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
    </eOperations>
    <eOperations name="getRelTypesOnSource" ordered="false" upperBound="-1" eType="#//ElementType">
      <eParameters name="source" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
    </eOperations>
    <eOperations name="getRelTypesOnTarget" ordered="false" upperBound="-1" eType="#//ElementType">
      <eParameters name="target" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
    </eOperations>
    <eOperations name="getRelTypesOnSourceAndTarget" ordered="false" upperBound="-1"
        eType="#//ElementType">
      <eParameters name="source" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
      <eParameters name="target" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
    </eOperations>
    <eOperations name="getRelTypesForSREOnTarget" ordered="false" upperBound="-1"
        eType="#//ElementType">
      <eParameters name="target" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
    </eOperations>
    <eOperations name="getRelTypesForSREOnSource" ordered="false" upperBound="-1"
        eType="#//ElementType">
      <eParameters name="source" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
    </eOperations>
    <eOperations name="getTypesForSource" ordered="false" upperBound="-1" eType="#//ElementType">
      <eParameters name="target" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
      <eParameters name="relationshipType" ordered="false" lowerBound="1" eType="#//ElementType"/>
    </eOperations>
    <eOperations name="getTypesForTarget" ordered="false" upperBound="-1" eType="#//ElementType">
      <eParameters name="source" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
      <eParameters name="relationshipType" ordered="false" lowerBound="1" eType="#//ElementType"/>
    </eOperations>
    <eOperations name="selectExistingElementForSource" ordered="false" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eParameters name="target" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
      <eParameters name="relationshipType" ordered="false" lowerBound="1" eType="#//ElementType"/>
    </eOperations>
    <eOperations name="selectExistingElementForTarget" ordered="false" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eParameters name="source" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
      <eParameters name="relationshipType" ordered="false" lowerBound="1" eType="#//ElementType"/>
    </eOperations>
    <eOperations name="getTypesForPopupBar" ordered="false" upperBound="-1" eType="#//ElementType">
      <eParameters name="host" ordered="false" lowerBound="1" eType="#//IAdaptable"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IProvider" instanceClassName="org.eclipse.gmf.runtime.common.core.service.IProvider"
      abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>From package serviceprovider.&lt;/p>"/>
    </eAnnotations>
    <eOperations name="provides" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="operation" ordered="false" lowerBound="1" eType="#//IOperation"/>
    </eOperations>
    <eOperations name="addProviderChangeListener" ordered="false" lowerBound="1">
      <eParameters name="listener" ordered="false" lowerBound="1" eType="#//IProviderChangeListener"/>
    </eOperations>
    <eOperations name="removeProviderChangeListener" ordered="false" lowerBound="1">
      <eParameters name="listener" ordered="false" lowerBound="1" eType="#//IProviderChangeListener"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="listener" ordered="false"
        upperBound="-1" eType="#//IProviderChangeListener"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IProviderChangeListener" instanceClassName="org.eclipse.gmf.runtime.common.core.service.IProviderChangeListener">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>From package serviceprovider.&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IOperation" instanceClassName="org.eclipse.gmf.runtime.common.core.service.IOperation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>From package serviceprovider.&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IAdaptable" instanceClassName="org.eclipse.core.runtime.IAdaptable">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>From package assistantapi.&lt;/p>"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementTypeFilter" eSuperTypes="../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter">
    <eOperations name="getElementType" ordered="false" lowerBound="1" eType="#//ElementType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getProvider" ordered="false" lowerBound="1" eType="#//ModelingAssistantProvider">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedVisibility" value="true"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementTypeID" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" ordered="false"
        unique="false" lowerBound="1" eType="#//ElementType" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" ordered="false"
        lowerBound="1" eType="#//ModelingAssistantProvider" changeable="false" volatile="true"
        transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
