<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eefadvancedcontrols" nsURI="http://www.eclipse.org/papyrus/sirius/properties/eef/advanced/controls"
    nsPrefix="eef-advanced-controls">
  <eClassifiers xsi:type="ecore:EClass" name="EEFExtEditableReferenceDescription"
      eSuperTypes="../../org.eclipse.eef.ext.widgets.reference/model/eef-ext-widgets-reference.ecore#//EEFExtReferenceDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="removeExpression" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createExpression" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="browseExpression" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEFContainerBorderDescription" eSuperTypes="../../org.eclipse.eef/model/eef.ecore#//EEFContainerDescription ../../org.eclipse.eef/model/eef.ecore#//EEFControlDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelExpression" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEFLanguageExpressionDescription" eSuperTypes="../../org.eclipse.eef/model/eef.ecore#//EEFWidgetDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="EEFProfileApplicationDescription" eSuperTypes="../../org.eclipse.eef/model/eef.ecore#//EEFWidgetDescription"/>
  <eClassifiers xsi:type="ecore:EClass" name="EEFStereotypeApplicationDescription"
      eSuperTypes="../../org.eclipse.eef/model/eef.ecore#//EEFControlDescription ../../org.eclipse.eef/model/eef.ecore#//EEFContainerDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The label of the Widget visible by the end-users."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="helpExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The tooltip of the help icon visible by the end-users"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EEFInputContentPapyrusReferenceDescription"
      eSuperTypes="#//EEFExtEditableReferenceDescription">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputContentExpression"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
