<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="filters" nsURI="http://www.eclipse.org/Papyrus/2014/common/filters"
    nsPrefix="filters">
  <eClassifiers xsi:type="ecore:EClass" name="FilterReference" eSuperTypes="#//Filter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A filter that redirects to a referenced filter. Useful to reuse filters by reference in any&#xA;context where otherwise the filtered element doesn't support shared filters."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" ordered="false"
        lowerBound="1" eType="#//Filter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilter" ordered="false"
        eType="#//Filter" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Owning the indirect reference&#xA;lets a dependent model that uses&#xA;filters access all available child&#xA;creation extenders, when it cannot&#xA;access those extenders, itself."/>
      </eAnnotations>
      <eAnnotations source="subsets" references="#//FilterReference/filter"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter" abstract="true" interface="true">
    <eOperations name="matches" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean">
      <eParameters name="input" ordered="false" lowerBound="1" eType="#//Object"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Object" instanceClassName="java.lang.Object"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundFilter" eSuperTypes="#//Filter">
    <eOperations name="acyclic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A filter may not directly or indirectly compose itself."/>
      </eAnnotations>
      <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
        </eAnnotations>
      </eParameters>
      <eParameters name="context">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The cache of context-specific information."/>
        </eAnnotations>
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" ordered="false"
        lowerBound="1" upperBound="-1" eType="#//Filter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFilter" ordered="false"
        upperBound="-1" eType="#//Filter" containment="true">
      <eAnnotations source="subsets" references="#//CompoundFilter/filter"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
        lowerBound="1" eType="#//OperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="and"/>
    <eLiterals name="or" value="1"/>
    <eLiterals name="xor" value="2"/>
    <eLiterals name="not" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Equals" eSuperTypes="#//Filter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="object" ordered="false"
        lowerBound="1" eType="#//Object"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteredElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" ordered="false"
        eType="#//Filter" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
