<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="filters" nsURI="http://www.eclipse.org/Papyrus/2014/uml/filters"
    nsPrefix="umlfilters">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="umlfilters"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileApplied" eSuperTypes="../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Filter">
    <eOperations name="resolveProfile" ordered="false" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Profile">
      <eParameters name="context" ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.papyrus.infra.filters/model/filters.ecore#//Object"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileQualifiedName" ordered="false"
        eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profileURI" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
  </eClassifiers>
</ecore:EPackage>
