/*
 * generated by Xtext
 */
package org.eclipse.papyrus.uml.alf;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AlfUiInjectorProvider implements IInjectorProvider {

	public Injector getInjector() {
		return org.eclipse.papyrus.uml.alf.ui.internal.AlfActivator.getInstance().getInjector("org.eclipse.papyrus.alf.integration.Alf");
	}

}
