<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="BookStore" nsURI="http:///bookstore.ecore" nsPrefix="BookStore">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="bookstore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Book">
    <eOperations name="addAuthor" ordered="false" lowerBound="1">
      <eParameters name="author" ordered="false" lowerBound="1" eType="#//Author"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        upperBound="-1" eType="#//Author" eOpposite="#//Author/book"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" lowerBound="1"
        eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editor" ordered="false"
        upperBound="-1" eType="#//Editor" eOpposite="#//Editor/book"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Author" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authorName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" ordered="false" upperBound="-1"
        eType="#//Book" eOpposite="#//Book/author"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eOperations name="isBirthday" ordered="false" lowerBound="1" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" ordered="false"
        lowerBound="1" eType="ecore:EDataType ../../../org.eclipse.uml2.types/model/Types.ecore#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
        eType="ecore:EClass ../../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Editor" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" ordered="false" upperBound="-1"
        eType="#//Book" eOpposite="#//Book/editor"/>
  </eClassifiers>
</ecore:EPackage>
